### ISSUE TITLE
[fix] 결과페이지_열차 '마이페이지' 디자인과 비슷하게 맞추기

### ISSUE THREAD

**Issue by JOYmet33** [B09-Galaxy/teamProject#27]
## To-Do
- [x] Tap, Card 색상 바꾸기 : blue-400 ->  [#0076be] 신한은행 파랑색
- [x] Year, Month, Day, Hour, Minute 변수 생성 (예: {Year}년 {Month}월 {Day}일)
- [x] 필요 없는 style 지우기
