### ISSUE TITLE
[feat] Search Page

### ISSUE THREAD

**Issue by munyeol-Yoon** [B09-Galaxy/teamProject#5]
## To-Do
- [x] 검색 페이지 및 컴포넌트 셋업
- [ ] 지역 입력 데이터 코드화
- [x] 입력 데이터 전역상태 추가
- [x] 검색 페이지 스타일 추가

### 기타 알려야 하는 상황을 적어주세요

선택 구현 사항 캘린더
